[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "next dev"
  port = 3002
  targetPort = 3000
  framework = "next"
  publish = ".next"
  functions = "netlify/functions"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
